using HosipitalManager.MVVM.Models;
using HospitalManager.MVVM.Models;
using System.Collections.Generic;

namespace HosipitalManager.MVVM.Services
{
    public class MedicineService
    {
        // Hàm trả về danh sách 100 loại thuốc (Giả lập Database)
        public List<MedicineProduct> GetMedicineCatalog()
        {
            return new List<MedicineProduct>
            {
                new MedicineProduct { Name = "Paracetamol 500mg", Unit = "Viên", UnitPrice = 500 },
                new MedicineProduct { Name = "Panadol Extra", Unit = "Viên", UnitPrice = 2500 },
                new MedicineProduct { Name = "Panadol Cold & Flu", Unit = "Viên", UnitPrice = 3500 },
                new MedicineProduct { Name = "Efferalgan 500mg", Unit = "Viên", UnitPrice = 800 },
                new MedicineProduct { Name = "Tiffy Dey", Unit = "Viên", UnitPrice = 2200 },
                new MedicineProduct { Name = "Decolgen Forte", Unit = "Viên", UnitPrice = 1800 },
                new MedicineProduct { Name = "Hapacol 650", Unit = "Viên", UnitPrice = 1200 },
                new MedicineProduct { Name = "Amoxicillin 500mg", Unit = "Viên", UnitPrice = 1500 },
                new MedicineProduct { Name = "Klamentin 1g (Amox + Acid Clavulanic)", Unit = "Viên", UnitPrice = 8500 },
                new MedicineProduct { Name = "Zinnat 500mg", Unit = "Viên", UnitPrice = 13500 },
                new MedicineProduct { Name = "Cefixim 200mg", Unit = "Viên", UnitPrice = 6500 },
                new MedicineProduct { Name = "Bactamox 750mg", Unit = "Viên", UnitPrice = 5500 },
                new MedicineProduct { Name = "Azithromycin 500mg", Unit = "Viên", UnitPrice = 9500 },
                new MedicineProduct { Name = "Medixin 500mg (Cephalexin)", Unit = "Viên", UnitPrice = 1200 },
                new MedicineProduct { Name = "Ciprofloxacin 500mg", Unit = "Viên", UnitPrice = 2500 },
                new MedicineProduct { Name = "Berberin 100mg", Unit = "Viên", UnitPrice = 300 },
                new MedicineProduct { Name = "Bổ sung Vitamin C 500mg", Unit = "Viên", UnitPrice = 800 },
                new MedicineProduct { Name = "Vitamin B1-B6-B12 (Neurobion)", Unit = "Viên", UnitPrice = 3500 },
                new MedicineProduct { Name = "B Complex + C", Unit = "Viên", UnitPrice = 1500 },
                new MedicineProduct { Name = "Dabroston (B1+B6+B12)", Unit = "Viên", UnitPrice = 2500 },
                new MedicineProduct { Name = "Eugica (siro ho)", Unit = "Lọ 100ml", UnitPrice = 28000 },
                new MedicineProduct { Name = "Prospan (siro ho thảo dược)", Unit = "Lọ 100ml", UnitPrice = 85000 },
                new MedicineProduct { Name = "Dorithricin", Unit = "Viên ngậm", UnitPrice = 4500 },
                new MedicineProduct { Name = "Strepsils Cool", Unit = "Viên ngậm", UnitPrice = 2500 },
                new MedicineProduct { Name = "Tyrotab (Levothyroxin 100mcg)", Unit = "Viên", UnitPrice = 2200 },
                new MedicineProduct { Name = "Glucophage 850mg (Metformin)", Unit = "Viên", UnitPrice = 1500 },
                new MedicineProduct { Name = "Dianorm 80/850 (Gliclazide + Metformin)", Unit = "Viên", UnitPrice = 3500 },
                new MedicineProduct { Name = "Forxiga 10mg (Dapagliflozin)", Unit = "Viên", UnitPrice = 28500 },
                new MedicineProduct { Name = "Jardiance 25mg", Unit = "Viên", UnitPrice = 32000 },
                new MedicineProduct { Name = "Coversyl 5mg", Unit = "Viên", UnitPrice = 12500 },
                new MedicineProduct { Name = "Amlor 5mg (Amlodipine)", Unit = "Viên", UnitPrice = 1800 },
                new MedicineProduct { Name = "Lipitor 20mg (Atorvastatin)", Unit = "Viên", UnitPrice = 14500 },
                new MedicineProduct { Name = "Vastanic 20mg", Unit = "Viên", UnitPrice = 6500 },
                new MedicineProduct { Name = "Concor 5mg (Bisoprolol)", Unit = "Viên", UnitPrice = 8500 },
                new MedicineProduct { Name = "Nebilet 5mg", Unit = "Viên", UnitPrice = 15500 },
                new MedicineProduct { Name = "Nexium 40mg", Unit = "Viên", UnitPrice = 18500 },
                new MedicineProduct { Name = "Omez 20mg (Omeprazole)", Unit = "Viên", UnitPrice = 2500 },
                new MedicineProduct { Name = "Motilium-M 10mg", Unit = "Viên", UnitPrice = 4500 },
                new MedicineProduct { Name = "Domridon 10mg", Unit = "Viên", UnitPrice = 1800 },
                new MedicineProduct { Name = "Phosphalugel", Unit = "Gói", UnitPrice = 5500 },
                new MedicineProduct { Name = "Smecta", Unit = "Gói", UnitPrice = 4500 },
                new MedicineProduct { Name = "Enterogermina", Unit = "Ống 5ml", UnitPrice = 11500 },
                new MedicineProduct { Name = "BioGaia Protectis", Unit = "Ống", UnitPrice = 18500 },
                new MedicineProduct { Name = "Bình vị thái minh", Unit = "Viên", UnitPrice = 4500 },
                new MedicineProduct { Name = "Dạ dày chữ P (Phúc Lộc Thọ)", Unit = "Viên", UnitPrice = 3800 },
                new MedicineProduct { Name = "Boganic Forte", Unit = "Viên", UnitPrice = 5500 },
                new MedicineProduct { Name = "Silymarin (Legalon 140)", Unit = "Viên", UnitPrice = 12500 },
                new MedicineProduct { Name = "Mobimed 15mg (Meloxicam)", Unit = "Viên", UnitPrice = 3500 },
                new MedicineProduct { Name = "Mobic 7.5mg", Unit = "Viên", UnitPrice = 8500 },
                new MedicineProduct { Name = "Voltaren 50mg (Diclofenac)", Unit = "Viên", UnitPrice = 2500 },
                new MedicineProduct { Name = "Myonal 50mg (Eperisone)", Unit = "Viên", UnitPrice = 6500 },
                new MedicineProduct { Name = "Decontractyl 250mg", Unit = "Viên", UnitPrice = 4500 },
                new MedicineProduct { Name = "Diazepam 5mg", Unit = "Viên", UnitPrice = 1200 },
                new MedicineProduct { Name = "Rotundin 30mg", Unit = "Viên", UnitPrice = 800 },
                new MedicineProduct { Name = "Stresam 50mg", Unit = "Viên", UnitPrice = 9500 },
                new MedicineProduct { Name = "Dogmatil 50mg", Unit = "Viên", UnitPrice = 4500 },
                new MedicineProduct { Name = "Dabigatran 150mg (Pradaxa)", Unit = "Viên", UnitPrice = 48500 },
                new MedicineProduct { Name = "Xarelto 20mg (Rivaroxaban)", Unit = "Viên", UnitPrice = 52500 },
                new MedicineProduct { Name = "Clopidogrel 75mg (Plavix)", Unit = "Viên", UnitPrice = 18500 },
                new MedicineProduct { Name = "Tanaflukol 75mg", Unit = "Viên", UnitPrice = 5500 },
                new MedicineProduct { Name = "Menison 16mg", Unit = "Viên", UnitPrice = 3500 },
                new MedicineProduct { Name = "Prednison 5mg", Unit = "Viên", UnitPrice = 600 },
                new MedicineProduct { Name = "Medrol 16mg", Unit = "Viên", UnitPrice = 6500 },
                new MedicineProduct { Name = "Arcoxia 90mg", Unit = "Viên", UnitPrice = 18500 },
                new MedicineProduct { Name = "Singulair 10mg (Montelukast)", Unit = "Viên", UnitPrice = 12500 },
                new MedicineProduct { Name = "Ventolin Inhaler 100mcg", Unit = "Bình xịt", UnitPrice = 95000 },
                new MedicineProduct { Name = "Seretide Evohaler 25/250", Unit = "Bình xịt", UnitPrice = 285000 },
                new MedicineProduct { Name = "Symbicort Turbuhaler 160/4.5", Unit = "Bình hít", UnitPrice = 485000 },
                new MedicineProduct { Name = "Salbutamol 2mg", Unit = "Viên", UnitPrice = 400 },
                new MedicineProduct { Name = "Bromhexin 8mg", Unit = "Viên", UnitPrice = 600 },
                new MedicineProduct { Name = "Acetylcystein 200mg (Mucomyst)", Unit = "Gói", UnitPrice = 3500 },
                new MedicineProduct { Name = "Telfast 180mg (Fexofenadine)", Unit = "Viên", UnitPrice = 8500 },
                new MedicineProduct { Name = "Clarityne 10mg", Unit = "Viên", UnitPrice = 4500 },
                new MedicineProduct { Name = "Cetirizin 10mg", Unit = "Viên", UnitPrice = 800 },
                new MedicineProduct { Name = "Loratadin 10mg", Unit = "Viên", UnitPrice = 600 },
                new MedicineProduct { Name = "Rowatinex", Unit = "Viên", UnitPrice = 12500 },
                new MedicineProduct { Name = "Uroxacin 200mg (Norfloxacin)", Unit = "Viên", UnitPrice = 2500 },
                new MedicineProduct { Name = "Cystex (trị nhiễm trùng tiết niệu)", Unit = "Viên", UnitPrice = 8500 },
                new MedicineProduct { Name = "Flagyl 250mg (Metronidazol)", Unit = "Viên", UnitPrice = 800 },
                new MedicineProduct { Name = "Nizoral 200mg (Ketoconazole)", Unit = "Viên", UnitPrice = 6500 },
                new MedicineProduct { Name = "Fluconazole 150mg", Unit = "Viên", UnitPrice = 12500 },
                new MedicineProduct { Name = "Daktarin Oral Gel", Unit = "Tuýp 15g", UnitPrice = 45000 },
                new MedicineProduct { Name = "Bảo vệ gan Hepius", Unit = "Viên", UnitPrice = 5800 },
                new MedicineProduct { Name = "Sâm Alipas Platinum", Unit = "Viên", UnitPrice = 18500 },
                new MedicineProduct { Name = "Hoạt huyết dưỡng não DHG", Unit = "Viên", UnitPrice = 4500 },
                new MedicineProduct { Name = "Ginkgo Biloba 120mg", Unit = "Viên", UnitPrice = 3500 },
                new MedicineProduct { Name = "Omega 3 Fish Oil 1000mg", Unit = "Viên", UnitPrice = 2800 },
                new MedicineProduct { Name = "Calcium Corbiere", Unit = "Ống 10ml", UnitPrice = 8500 },
                new MedicineProduct { Name = "Canxi Nano Gold", Unit = "Viên", UnitPrice = 4500 },
                new MedicineProduct { Name = "Elevit (bà bầu)", Unit = "Viên", UnitPrice = 18500 },
                new MedicineProduct { Name = "Prenacy Gold", Unit = "Viên", UnitPrice = 6500 },
                new MedicineProduct { Name = "DHA Bio Island cho bé", Unit = "Viên", UnitPrice = 9500 },
                new MedicineProduct { Name = "KidCalci (canxi cho trẻ)", Unit = "Ống 10ml", UnitPrice = 7500 },
                new MedicineProduct { Name = "Zinc 10mg (kẽm)", Unit = "Viên", UnitPrice = 1200 },
                new MedicineProduct { Name = "Siro PediaKid Vitamin D3", Unit = "Lọ 125ml", UnitPrice = 285000 },
                new MedicineProduct { Name = "Băng cá nhân Urgo", Unit = "Miếng", UnitPrice = 1500 },
                new MedicineProduct { Name = "Nước muối sinh lý NaCl 0.9%", Unit = "Ống 10ml", UnitPrice = 1500 },
                new MedicineProduct { Name = "Cồn y tế 70 độ", Unit = "Chai 500ml", UnitPrice = 35000 },
                new MedicineProduct { Name = "Oxy già 3%", Unit = "Chai 60ml", UnitPrice = 12000 },
                new MedicineProduct { Name = "Bông y tế 100g", Unit = "Gói", UnitPrice = 18000 },
                new MedicineProduct { Name = "Gạc y tế vô trùng", Unit = "Miếng", UnitPrice = 2500 },
                new MedicineProduct { Name = "Thuốc nhỏ mắt V.Rohto", Unit = "Lọ 12ml", UnitPrice = 25000 },
                new MedicineProduct { Name = "Thuốc nhỏ mắt Osla", Unit = "Lọ 10ml", UnitPrice = 35000 }
            };
        }
    }
}